{{- if ne .Release.Namespace .Values.operatorNamespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-osd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-mgr
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rook-ceph-cmd-reporter
{{- end }}
