name: Release
on: release
jobs:

  build:
    name: Publish artifacts
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: run build
        run: make -j4 IMAGES='ceph' build

      - run: pwd; ls -l

      - name: upload ghr
        uses: fnkr/github-action-ghr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_PATH: ./images/ceph/operator.tgz
